apiVersion: alertmanager.keikoproj.io/v1alpha1
kind: AlertsConfig
metadata:
  name: alertsconfig-sample2
spec:
  # Add fields here
    globalParams:
      foo: status.health
      bar: severe
    globalGVK:
      group: alertmanager.keikoproj.io
      version: v1alpha1
      kind: WavefrontAlert
    alerts:
      wavefrontalert-sample3:
        params:
          foo: status.health
          bar: severe
          zzz: status.health
      wavefrontalert-sample2:
        params:
          foo: status.health
