name: Cluster Integration Tests

on:
  # Run only on direct pushes to master (post-merge verification)
  push:
    branches: [ master ]
  # Run for PRs targeting master (pre-merge verification)
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

# Prevent duplicate workflow runs for PRs from branches in the same repository
# This avoids running the workflow twice when a PR branch is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kind-test:
    name: Kubernetes In Docker Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          cache: true
          
      - name: Install required tools
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
          
      - name: Generate mocks
        run: |
          make mock
          
      - name: Setup Kind Cluster
        uses: helm/kind-action@v2
        with:
          version: v0.20.0
          cluster_name: alert-manager-test
          
      - name: Run tests with Kind cluster
        run: |
          make test-kind
          
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./cover.out
