name: Comprehensive Testing

on:
  # Run only on direct pushes to master (post-merge verification)
  push:
    branches: [ master ]
  # Run for PRs targeting master (pre-merge verification)
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

# Prevent duplicate workflow runs for PRs from branches in the same repository
# This avoids running the workflow twice when a PR branch is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit & Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go-version: [1.21.x]
        arch: [amd64, arm64]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install required tools
        run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          go install github.com/golang/mock/mockgen@v1.6.0
          
      - name: Generate mocks
        run: |
          make mock
          
      - name: Setup environment and run comprehensive tests
        run: |
          make ci-test
          
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./cover.out

  integration-test:
    name: Kind Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x
          
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.4.0
        
      - name: Run integration tests
        run: |
          make test-kind