name: Comprehensive Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: Unit & Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go-version: [1.21.x]
        arch: [amd64, arm64]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install required tools
        run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          
      - name: Setup environment and run comprehensive tests
        run: |
          make ci-test
          
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./cover.out

  integration-test:
    name: Kind Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x
          
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.4.0
        
      - name: Run integration tests
        run: |
          make test-kind